[package]
name = "example_happ"
version = "0.0.1"
edition = "2018"

[lib]
name = "example_happ"
crate-type = ["cdylib", "rlib"]

[dependencies]
hdk = "0.0.115"
# holo_hash = "*"
serde = "1"

[dev-dependencies]
holochain = { version = "0.0.115", default-features = false, features = ["test_utils"] }
